### ISSUE TITLE
For mye Frodekode

### ISSUE THREAD

**Issue by robinnydahl** [skulstadv/School#1]
Vennligst rydd bort litt mer frodekode. Ser du fjernet en del, men vi trenger å fjerne mer. Denne blir ikke godkjent med så mye dritt...

**Comment by skulstadv** [comment]
Sjansen for å få godkjent oblig er invers proporsjonal med antall linjer fjernet fra rammeverket, frodekoden blir værende.

**Comment by robinnydahl** [comment]
hahahhahahaha! Du sier noe.
